const products = [
  {
    id: "mac",
    name: "MacBook Air 13″ and 15″",
    chip: "M4 chip",
    description: "Strikingly thin and fast so you can work, play, or create anywhere.",
    category: "laptop",
    colors: ["#a8c4e0", "#d4b896", "#c8c8c8", "#1a1a1a"],
    image: "/mbp.jpg",
  },
  {
    id: "mac",
    name: "MacBook Pro 14″ and 16″",
    chip: "M5, M4 Pro, or M4 Max chip",
    description: "The most advanced Mac laptops for demanding workflows.",
    category: "laptop",
    colors: ["#1a1a1a", "#c8c8c8"],
    image: "/mba.jpg",
  },
  {
    id: "mac",
    name: "iMac",
    chip: "M4 chip",
    description: "A stunning all-in-one desktop for creativity and productivity.",
    category: "desktop",
    colors: ["#5b8fe8", "#e05f5f", "#e0a05f", "#6cbf6c", "#c15fe0", "#5fcce0", "#d4b896"],
    image: "/imac.jpg",
  },
  {
    id: "mac",
    name: "Mac mini",
    chip: "M4 or M4 Pro chip",
    description: "The mini-est, most affordable Mac with mighty performance.",
    category: "desktop",
    colors: ["#c8c8c8"],
    image: "/mac_mini.jpg",
  },
  {
    id: "mac",
    name: "Mac Studio",
    chip: "M4 Max or M4 Ultra chip",
    description: "Supercharged for pros who push the limits.",
    category: "desktop",
    colors: ["#c8c8c8"],
    image: "/mac_studio.jpg",
  },
  {
    id: "mac",
    name: "Mac Pro",
    chip: "M4 Ultra chip",
    description: "A powerhouse built for the most complex, ambitious workflows.",
    category: "desktop",
    colors: ["#c8c8c8"],
    image: "/mac_pro.jpg",
  },
  {
    id: "mac",
    name: "Studio Display",
    chip: "",
    description: "A 5K Retina display with stellar camera and audio.",
    category: "display",
    colors: [],
    image: "/pro_display.jpg",
  },
  {
    id: "mac",
    name: "Pro Display XDR",
    chip: "",
    description: "An advanced 6K XDR display for pro workflows.",
    category: "display",
    colors: [],
    image: "/studio_display.jpg",
  },
];

export default products;